CREATE TABLE IF NOT EXISTS OTP_VERIFICACION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    codigo VARCHAR(6) NOT NULL,
    proposito VARCHAR(50) NOT NULL, -- 'CAMBIO_PASSWORD' o 'REGISTRO_USUARIO'
    expira_en DATETIME NOT NULL,
    utilizado BOOLEAN DEFAULT FALSE,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
