
CREATE TABLE IF NOT EXISTS LOG_CORREOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    correo_destino VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL, -- 'OTP', 'REGISTRO', 'TEST'
    estado VARCHAR(20) NOT NULL, -- 'ENVIADO', 'FALLIDO'
    error_mensaje TEXT,
    cedula_asociada VARCHAR(10) -- Para rastrear intentos por cédula
);

CREATE TABLE IF NOT EXISTS LOG_INTENTOS_CEDULA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    cedula VARCHAR(10) NOT NULL,
    tipo_accion VARCHAR(50) NOT NULL, -- 'LOGIN_FALLIDO', 'RECUPERACION_FALLIDA', 'VALIDACION_CEDULA'
    exitoso BOOLEAN DEFAULT FALSE,
    ip_address VARCHAR(45)
);
