
INSERT INTO ROLES (id, nombre) 
SELECT 6, 'Soporte TI' 
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE id = 6);

CREATE TABLE IF NOT EXISTS LOG_CORREOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    correo_destino VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    error_mensaje TEXT,
    cedula_asociada VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS LOG_INTENTOS_CEDULA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    cedula VARCHAR(10) NOT NULL,
    tipo_accion VARCHAR(50) NOT NULL,
    exitoso BOOLEAN DEFAULT FALSE,
    ip_address VARCHAR(45)
);
