INSERT INTO `CAT_MEDICAMENTOS` (`nombre_generico`, `forma_farmaceutica`, `concentracion`, `stock_minimo`) VALUES
('Paracetamol', 'Tableta', '500mg', 100),
('Paracetamol', 'Jarabe', '120mg/5ml', 50),
('Paracetamol', 'Solución Inyectable', '10mg/ml', 50),
('Ibuprofeno', 'Tableta', '400mg', 100),
('Ibuprofeno', 'Jarabe', '100mg/5ml', 50),
('Metamizol', 'Solución Inyectable', '1g/2ml', 100),
('Diclofenaco Sódico', 'Solución Inyectable', '75mg/3ml', 100),
('Ketorolaco', 'Solución Inyectable', '30mg/ml', 80),
('Tramadol', 'Solución Inyectable', '50mg/ml', 50),
('Morfina', 'Solución Inyectable', '10mg/ml', 20),
('Adrenalina', 'Solución Inyectable', '1mg/ml', 50),
('Atropina', 'Solución Inyectable', '1mg/ml', 50),
('Salbutamol', 'Solución para Nebulizar', '5mg/ml', 50),
('Salbutamol', 'Inhalador', '100mcg/dosis', 30),
('Bromuro de Ipratropio', 'Solución para Nebulizar', '0.25mg/ml', 30),
('Hidrocortisona', 'Polvo para Inyección', '100mg', 50),
('Dexametasona', 'Solución Inyectable', '4mg/ml', 50),
('Omeprazol', 'Polvo para Inyección', '40mg', 50),
('Metoclopramida', 'Solución Inyectable', '10mg/2ml', 50),
('Ondansetron', 'Solución Inyectable', '8mg/4ml', 40),
('Ceftriaxona', 'Polvo para Inyección', '1g', 50),
('Solución Salina Normal', 'Bolsa', '0.9% 1000ml', 100),
('Lactato de Ringer', 'Bolsa', '1000ml', 100),
('Dextrosa en Agua', 'Bolsa', '5% 1000ml', 50);
